config/routes.rb
Rails.application.routes.draw do
  
  resources :goals do 
    member do
      post :complete, to: 'goals#complete'
    end
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users
  

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :goal, :user_id, presence: true
  validates :secret, :completed, inclusion: { :in => [true, false] }

  before_validation do
    self.completed = false if completed.nil?
    self.secret = false if secret.nil?
  end
  
  belongs_to :user
  #has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true, message: "must be at least 6 characters"}
  validates :username, uniqueness: true
  
  before_validation do
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
  
  has_many :goals
  #has_many :comments
  
  def self.find_by_credentials(username, password)
    user = find_by(username: username)
    user.try(:is_password?, password) ? user : nil
  end

  
  def password
    @password
  end
  
  def password=(value)
    self.password_digest = BCrypt::Password.create(value)
    @password = value
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    save!
    session_token
  end
  
  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :signed_in?
  
  private
  
  def current_user
    @current_user ||= User.find_by(session_token: session[:token])
  end
  
  def signed_in?
    !!current_user
  end
  
  def login!(user)
    session[:token] = user.session_token
  end
  
  def logout!
    current_user.try(:reset_session_token!)
    session[:token] = nil
  end
  
  def require_signed_in
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_signed_in
  before_action :authorized, only: [:edit, :update, :destroy, :complete]
  
  def new
    @goal = Goal.new
  end
  
  def show
    @goal = Goal.find(params[:id])
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    
    if @goal.save
      redirect_to user_url(@goal.user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end
  
  def edit
  end
  
  def update    
    if @goal.update(goal_params)
      redirect_to user_url(@goal.user_id)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @goal.destroy
    redirect_to user_url(@goal.user_id)
  end
  
  def complete
    @goal.update!(completed: true)
    redirect_to user_url(@goal.user_id)
  end
    
  private
  
  def goal_params
    params.require(:goal).permit(:goal, :secret, :completed)
  end
  
  def authorized
    @goal = current_user.goals.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:errors] = ["You are not authorized"]
    redirect :back
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      @user = User.new
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end
  
  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
  
  def goal_edit_button(goal)
    if current_user == goal.user
      link_to "edit goal", edit_goal_url(goal)
    end
  end
  
  def goal_delete_button(goal)
    if current_user == goal.user
      button_to "delete goal", goal_url(goal), method: :delete 
    end
  end
  
  def goal_completed(goal)
    if goal.completed
      ' completed'
    elsif current_user == goal.user
      button_to('complete goal', complete_goal_url(goal))
    end
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<%= form_for @goal do |f| %>
  <%= f.label :goal, 'goal' %>
  <%= f.password_field :goal %>
  
  <%= f.label :secret, 'secret' %>
  <%= f.check_box :secret %>
  
  <%= f.submit %>
<% end %>

app/views/goals/_goal.html.erb
<%= link_to goal.goal, goal_url(goal) %>

<%= goal_completed(goal) %>
<%= goal_edit_button(goal) %>
<%= goal_delete_button(goal) %>

app/views/goals/edit.html.erb
Edit Goal
<%= render 'form' %>

app/views/goals/new.html.erb
New Goal
<%= render 'form' %>

app/views/goals/show.html.erb
<%= render @goal %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalSetter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <h1>Goal Setter</h1>
  <ul>
    <li><%= link_to 'Users', users_url %></li>
    <% if signed_in? %>
      <li><%= current_user.username %></li>
      <li><%= button_to 'Sign Out', session_url, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Sign In', new_session_url %></li>
      <li><%= link_to 'Sign Up', new_user_url %></li>
    <% end %>
  </ul>
</nav>
  <main>
    <div class="errors">
      <ul>
        <% if flash[:errors] %>
          <% flash[:errors].each do |error|  %>
            <li><%= error %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  
<%= yield %>

  </main>
  
  <embed src="http://www.sounddogs.com/previews/2179/mp3/187732_SOUNDDOGS__fi.mp3" loop="true" autostart="true" hidden="true" />
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, url: action do |f| %>
  <%= f.label :username, 'username' %>
  <%= f.password_field :username %>
  
  <%= f.label :password, 'password' %>
  <%= f.password_field :password %>
  
  <%= f.submit button_text %>
<% end %>

app/views/users/index.html.erb
<h3>User Directory</h3>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user_url(user) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h3>New user</h3>
<%= render 'form', action: users_url, button_text: 'Create User' %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<%= link_to 'new goal', new_goal_url %>
<ul>
<% @user.goals.each do |goal| %>
  <% next if goal.secret %>
  <li><%= render goal %></li>
<% end %>
</ul>